# Generated by Django 4.1.2 on 2022-10-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('short_bio', models.CharField(blank=True, max_length=256, null=True)),
                ('long_bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('advocate_years_exp', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advocates.advocate')),
            ],
        ),
    ]
