# Generated by Django 4.1.2 on 2022-10-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('short_bio', models.CharField(blank=True, max_length=256, null=True)),
                ('long_bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('advocate_years_exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='')),
                ('summary', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.advocate')),
            ],
        ),
        migrations.AddField(
            model_name='advocate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
