# Generated by Django 4.1.2 on 2022-10-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_advocate_github_advocate_twitter_advocate_youtube_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='long_bio',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='short_bio',
            field=models.CharField(default='', max_length=256),
        ),
    ]
