# Generated by Django 4.1.2 on 2022-10-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_advocate_long_bio_alter_advocate_short_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='short_bio',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='advocate_years_exp',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='github',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='long_bio',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='youtube',
        ),
        migrations.AddField(
            model_name='advocate',
            name='username',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
